### ISSUE TITLE
Cannot import Module

### ISSUE THREAD

**Issue by dynacorp** [Flutterwave/Flutterwave-Angular-v3#1]
So apparently you cannot import **FlutterwaveModule** in app module as stated in the usage description **import FlutterwaveModule from "flutterwave-angular-v3"**. It should be **import {FlutterwaveModule} from "flutterwave-angular-v3"**

**Comment by kenny-io** [comment]
Thank you @dynacorp we are looking into this and will make any necessary updates as soon as possible.

**Comment by Corvus97** [comment]
Hello @dynacorp , 

Thanks for bringing this to our attention.

Please note that this issue has been fixed. Kindly `run npm` update to get the fixes on your angular package.

Regards,
Cornelius.
