### ISSUE TITLE
Uncaught (in promise): Error: inject() must be called from an injection context

### ISSUE THREAD

**Issue by arahmancsd** [Flutterwave/Flutterwave-Angular-v3#11]
I have recently tried to implment Flutterwave in my angular ionic project. However, I am receiving below error when adding the Flutterwave as a service in the constructor.

import { Flutterwave, InlinePaymentOptions, PaymentSuccessResponse } from "flutterwave-angular-v3";

constructor(
    private routeChangeSvc: DashboardRouteChangeService,
    private router: Router,
    private activatedRoute: ActivatedRoute,
    private toastCtrl: ToastController,
    private flutterwave: Flutterwave
  ) { }

core.js:6479 ERROR Error: Uncaught (in promise): Error: inject() must be called from an injection context
Error: inject() must be called from an injection context
    at injectInjectorOnly (core.js:4745)
    at Module.ɵɵinject (core.js:4755)
    at Object.Flutterwave_Factory [as factory] (flutterwave-angular-v3.js:172)
    at R3Injector.hydrate (core.js:11437)
    at R3Injector.get (core.js:11256)
    at NgModuleRef$1.get (core.js:25365)
    at R3Injector.get (core.js:11267)
    at NgModuleRef$1.get (core.js:25365)
    at R3Injector.get (core.js:11267)
    at NgModuleRef$1.get (core.js:25365)
    at resolvePromise (zone.js:1255)
    at resolvePromise (zone.js:1209)
    at zone.js:1321
    at ZoneDelegate.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28692)
    at ZoneDelegate.invokeTask (zone.js:433)
    at Zone.runTask (zone.js:205)
    at drainMicroTaskQueue (zone.js:620)
    at ZoneTask.invokeTask [as invoke] (zone.js:520)
    at invokeTask (zone.js:1656)

zone.js:209 Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
    at HTMLDivElement.Element.remove (v3.js:1)
    at ion-ripple-effect.entry.js:82
    at timer (zone.js:3083)
    at ZoneDelegate.invokeTask (zone.js:434)
    at Zone.runTask (zone.js:205)
    at ZoneTask.invokeTask (zone.js:516)
    at ZoneTask.invoke (zone.js:505)
    at data.args.<computed> (zone.js:3063)
    Element.remove @ v3.js:1
    (anonymous) @ ion-ripple-effect.entry.js:82
    timer @ zone.js:3083
    ZoneDelegate.invokeTask @ zone.js:434
    Zone.runTask @ zone.js:205
    ZoneTask.invokeTask @ zone.js:516
    ZoneTask.invoke @ zone.js:505
    data.args.<computed> @ zone.js:3063
    setTimeout (async)
    scheduleTask @ zone.js:3065
    ZoneDelegate.scheduleTask @ zone.js:421
    Zone.scheduleTask @ zone.js:248
    Zone.scheduleMacroTask @ zone.js:271
    scheduleMacroTaskWithCurrentZone @ zone.js:716
    (anonymous) @ zone.js:3107
    proto.<computed> @ zone.js:1015
    removeRipple @ ion-ripple-effect.entry.js:81
    (anonymous) @ ion-ripple-effect.entry.js:60
    (anonymous) @ tap-click-cc1ae2b2.js:99
    ZoneDelegate.invoke @ zone.js:400
    Zone.run @ zone.js:160
    (anonymous) @ zone.js:1318
    ZoneDelegate.invokeTask @ zone.js:434
    Zone.runTask @ zone.js:205
    drainMicroTaskQueue @ zone.js:620
    Promise.then (async)
    scheduleMicroTask @ zone.js:603
    ZoneDelegate.scheduleTask @ zone.js:424
    Zone.scheduleTask @ zone.js:248
    Zone.scheduleMicroTask @ zone.js:268
    scheduleResolveOrReject @ zone.js:1308
    resolvePromise @ zone.js:1246
    (anonymous) @ zone.js:1162
    Promise.then (async)
    (anonymous) @ zone.js:1514
    ZoneAwarePromise @ zone.js:1340
    Ctor.then @ zone.js:1513
    resolvePromise @ zone.js:1213
    (anonymous) @ zone.js:1321
    ZoneDelegate.invokeTask @ zone.js:434
    Zone.runTask @ zone.js:205
    drainMicroTaskQueue @ zone.js:620
    ZoneTask.invokeTask @ zone.js:520
    invokeTask @ zone.js:1656
    globalZoneAwareCaptureCallback @ zone.js:1714

**package.json**

"dependencies": {
    "@angular/common": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/forms": "~12.1.1",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "@ionic/angular": "^5.5.2",
    "@swimlane/ngx-datatable": "^20.0.0",
    "@types/multer": "^1.4.7",
    "flutterwave-angular-v3": "^1.2.1",
    "remove": "^0.1.5",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular-eslint/builder": "~12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@angular/language-service": "~12.0.1",
    "@ionic/angular-toolkit": "^4.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  },

**Comment by toybz** [comment]
Hello @arahmancsd 

Please verify if you have added the Flutterwave Module to your app base module.

Please see below code for sample:

import { FlutterwaveModule } from "flutterwave-angular-v3"
 
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FlutterwaveModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})

**Comment by nkukehenry** [comment]
Hello, I have the same problem even when I have added that module to app.module

**Comment by toybz** [comment]
Hello @nkukehenry  @arahmancsd 
Please confirm if you still experienc this issue?

**Comment by nkukehenry** [comment]
Hello Rahmon,

This is still the case and the rother question i wanted to ask is:
How do i use a function in my component as a callback that can be triggered
after payment as i found that even after payment,
 I cannot call anything within my component as the 'this' in the component
( e.g this.paymentComplete() ) seems to point to FlutterwaveCheckoutK

Kindly go through this to understand my current issue.
I managed make it work by directly accessing the depency and posted a
payment but i can't call any code in my component after

Below is how i pulled it in:

[image: image.png]

Here is how i tried to set call back functions

[image: image.png]

Below is the data objects
[image: image.png]

Regards,
Henry Nkuke Mayanja
*Software Developer*
*Mobile: +256 705 596 470 | **| +256 777 245 670*
*https://www.solvertech.co <https://www.solvertech.co>*

**Comment by nkukehenry** [comment]
@Corvus97  the issue, I would love to be able to call another function in my component after payment , say a function name **'mycalBack".**
Curently and attempt to call it like: **this.mycallBack()** returns  **mycallBack is not a fucntion**

Please note that am attempting to use this an ionic app.

**Comment by toybz** [comment]
Hello @nkukehenry 

The SDK already provides this feature.
Kindly ensure you pass this param
`    callbackContext: this
`
as part of the parameters, you passed to the inlinePay(paymentParam) method.

Please see the code sample below : 

```
import { Component } from '@angular/core';
import {Flutterwave, InlinePaymentOptions, PaymentSuccessResponse} from "flutterwave-angular-v3";
 
@Component({
  selector: 'app-root',
  template: `<button (click)="makePayment()">Pay</button>`,
})
export class AppComponent {
 
 publicKey = "FLWPUBK_TEST-XXXXXXXXX";
 
  customerDetails = { name: 'Demo Customer  Name', email: 'customer@mail.com', phone_number: '08100000000'}
 
  customizations = {title: 'Customization Title', description: 'Customization Description', logo: 'https://flutterwave.com/images/logo-colored.svg'}
 
  meta = {'counsumer_id': '7898', 'consumer_mac': 'kjs9s8ss7dd'}
 
 paymentData: InlinePaymentOptions = {
    public_key: this.publicKey,
    tx_ref: this.generateReference(),
    amount: 10,
    currency: 'NGN',
    payment_options: 'card,ussd',
    redirect_url: '',
    meta: this.meta,
    customer: this.customerDetails,
    customizations: this.customizations,
    callback: this.makePaymentCallback,
    onclose: this.closedPaymentModal,
    callbackContext: this
  }
  //Inject the flutterwave service 
  constructor(private flutterwave: Flutterwave ) {
  }
  makePayment(){
    this.flutterwave.inlinePay(this.paymentData)
  }
  makePaymentCallback(response: PaymentSuccessResponse): void {
    console.log("Payment callback", response);
  }
  closedPaymentModal(): void {
    console.log('payment is closed');
  }
}
```
