### ISSUE TITLE
Cannot read property of null (remvedChild

### ISSUE THREAD

**Issue by swagasoft** [Flutterwave/Flutterwave-Angular-v3#12]
zone.js:209 Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
    at HTMLDivElement.Element.remove (v3.js:1)
    at ion-ripple-effect.entry.js:82

After installing flutterwave-angular-v3": "^1.2.0" on my project, the above error keeps showing on the console.

**Comment by toybz** [comment]
Hello @swagasoft  the error message is from the v3 inline script and not from the plugin.
We will inform the team to look into it. Please note that this has no effect on your payment and the SDK will
work as expected.
I will be closing this issue now.
