### ISSUE TITLE
Error: export 'WrappedValue' (imported as 'WrappedValue') was not found in '@angular/core'

### ISSUE THREAD

**Issue by ganiru** [Flutterwave/Flutterwave-Angular-v3#15]
I added this plugin to an Ionic Framework v5 capacitor app via `npm install flutterwave-angular-v3`, updated the app.module file, and imported it onto a component.

I then ran '`ionic cap sync`' to compile it, and I'm getting the error ..
`./node_modules/flutterwave-angular-v3/node_modules/@angular/common/__ivy_ngcc__/fesm2015/common.js:5725:15-32 - Error: export 'WrappedValue' (imported as 'WrappedValue') was not found in '@angular/core' (possible exports: ANALYZE_FOR_ENTRY_COMPONENTS, APP_BOOTSTRAP_LISTENER, APP_ID, APP_INITIALIZER, ApplicationInitStatus, ApplicationModule, ApplicationRef, Attribute, COMPILER_OPTIONS, CUSTOM_ELEMENTS_SCHEMA, ChangeDetectionStrategy, ChangeDetectorRef, Compiler, CompilerFactory,....`

How can I resolve this?

**Comment by toybz** [comment]
Hello @ganiru 

 Kindly include the following line in tsconfig.app.json under compilerOptions :

```
paths": { "@angular/*": [ "node_modules/@angular/*" ] }
```

Then restart server and try again
